In [1]:
import numpy as np 

# Análisis de Algoritmos de Ordenamiento

## 1. Introduction

El ordenamiento de datos es uno de los problemas fundamentales en ciencias de la computación, con aplicaciones en múltiples áreas como búsqueda, optimización y análisis de información. La eficiencia de los algoritmos de ordenamiento impacta directamente en el rendimiento de sistemas que manejan grandes volúmenes de datos.

En este trabajo se analizan e implementan distintos algoritmos de ordenamiento, con el objetivo de comparar su desempeño teórico y práctico. Se consideran tanto algoritmos clásicos como enfoques más eficientes, así como una aplicación del paradigma de eventos mediante el uso de sweep line algorithms.

---



## 2. Methods

### 2.1 Descripción de Algoritmos

A continuación se describen los algoritmos implementados:




In [80]:
list_n = np.random.randint(1,10,4)
print(list_n)

[2 7 3 1]


#### Bubble Sort

En cada pasada, el elemento más grande “flota” hacia el final del arreglo,
como una burbuja que sube a la superficie, de ahí el nombre.

Después de la primera pasada:

- el mayor elemento queda en la última posición.

Después de la segunda pasada:

- el segundo mayor queda en la penúltima posición.

Y así sucesivamente.

In [81]:
def bubble_sort(list_n):
    ordered_list = list_n.copy()
    list_len = len(ordered_list)
    for i in range(list_len):
        for j in range(list_len):
            
                

In [82]:
list_n

array([2, 7, 3, 1], dtype=int32)

In [83]:
bubble_sort(list_n)

array([2, 2, 1, 7], dtype=int32)


#### Selection Sort

[Describe aquí la idea general del algoritmo]

#### Counting Sort

[Describe aquí la idea general del algoritmo]

#### Quick Sort

[Describe aquí la idea general del algoritmo]

#### Merge Sort

[Describe aquí la idea general del algoritmo]

---

### 2.2 Sweep Line Algorithm

Se implementa un algoritmo basado en la técnica de barrido (sweep line), el cual permite resolver problemas mediante el procesamiento ordenado de eventos.

El enfoque consiste en:

* Representar cada evento como una llegada (+) o salida (−)
* Ordenar los eventos por tiempo
* Recorrerlos manteniendo un contador de eventos activos

[Explica aquí con tus palabras el problema de clientes simultáneos]

---

### 2.3 Implementación

Los algoritmos fueron implementados en Python, utilizando estructuras de datos básicas.

[Opcional: menciona decisiones de implementación]

---

### 2.4 Análisis de Complejidad

Se analiza la complejidad temporal de cada algoritmo en términos de:

* Mejor caso
* Caso promedio
* Peor caso

[Agrega aquí una tabla o descripción breve]

---

### 2.5 Configuración Experimental

Para evaluar el desempeño de los algoritmos, se realizaron pruebas con distintos tamaños de entrada.

* Tamaños de entrada: [ej. 100, 1000, 10000]
* Tipo de datos: [aleatorios, ordenados, etc.]
* Métrica: tiempo de ejecución

---

## 3. Results

A continuación se presentan los resultados obtenidos:

[Tabla de resultados]

[Opcional: gráficas]

---

## 4. Discussion

Los resultados obtenidos permiten observar diferencias claras entre los algoritmos analizados.

[Compara aquí resultados vs teoría]

[Explica comportamientos interesantes]

[Discute ventajas y desventajas]

---

## 5. Conclusion

En este trabajo se analizaron distintos algoritmos de ordenamiento desde un enfoque teórico y práctico.

[Resumen breve de hallazgos]

[Opcional: posibles mejoras o trabajo futuro]
